# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_R=3.3.2
    - CONDA_R=3.4.1
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "LbtU/ph5tLGI0fXKJj19SBhZrQTojagcaN0RtkGcNDWEMgPOxHgAcVGw7NzVqkypQ+8gNFErpA72nyasaB2YvVHke75hg9vLpUGJ+n1Cy57JKZcsQNYBd86h4mgQEJ/RppEnGM0pm5vhfGKlTTLD85RtzvYhVTuiXmh3fmq1NG+ivkBeI3Z1IhDlZswq67fvHR1qQ95nmXGR2rE4qBToS6dM1BwImKJxb0ZMVaR1tQH3RgZaiJqhGmMVs7caTU3U5GfTNenLpcg1uTziEX6ldcsdeHKoS5y4n0wi3/XzKnp5ktyWcAogD8jl6pvobza11zXc56rDxSDT09kCEw5HJ7Xug3xp5TcuP7gpwZXVb05rMNkPGhxYN9mWgEOPNcrIb9cq0mOe7kyRIiqZkW9NjCuYhMZsDWXrdQ1xkLPrhNDvFolQmjlXzZlnnUDd2jY7brQljHBcc2i2wNXSWl+66uiHCP8kfnYKqdDC/YYO2bPRhXsXs0zCzutGrggIh9iZIkrZIdwcoH9DKARXEis5X0cDenHVH9o8WXF10cNp0a8H38IQDT6pp6pGybg61fYZnFzeoEaOe6UaiTlMeGfpgMYYK0z3QJg8txqoGC6fRRyp0rhZxWHKXBICCwBYKMi2bauWTox5HeAwDbgnvfH4jBHEzXueFyhJDHrdnKrLdKA="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
