travis:
  secure:
    BINSTAR_TOKEN: sLFel+MwIGjIWj8ZYpFyhtIqZUQIWlbHs7itKw3iFdM2FhEsP0wST4+T88XJboj3E9UMX9ksFvvM1sVV8zRgLgYcYXniormY/1tZ5Zw06AoNmd5kGVFV7UHeAlhuTyMjtKMgBZw0Ph3XqUJ+DNwiGu1l9t9v6yvQE4TjC1IAbx0F8cfOr4aJC55sil5ilr5NKs0caPR2JzOKy44hA8VD4rsjhnwlMYG7BoWyGc0/KJyz3EYurAFhe75f6HjDCU482BWieytPAzPzRxvK1eED1Jx9gfSzUPQ2i0VEHVqYWEUW4eWlqozndL5JIgjcB32kJ9MazhW7ONu1K+2Qe5XFvSXiIxQxQsRLHSglCY5kV+wov18CvhQNndGD173qKj5Ea8kcG8O1lbEKp6bKIMPzOlLTFBFhQPPQC9WciTKjAIbFh7OaJ27KaDgB1UQEJq+JYUDqAB6Rm+gWU2D6xEBu0B4ybWl0EggUKUHzp1crFs0VBGH5xNChLXwmAWf1++s3mPOnJc3g5/zdinGWLo+zYpkZnUnzd5L030NgeHKqfOLSWlsBMI5gkFk89N32iOupvaquEj86AjWv4rRILqa8BFovpmnPC3oe0XBetzPMDvN1BwBPK9xpLWZPpTgCVuA9fojzhnfEpMXmSZSUoHWbXNq5RmhUGa0/vSZeobIwTH8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
