travis:
  secure:
    BINSTAR_TOKEN: JjYWsxA1mf1EEuEWcGLdqW++K0/wp8y0Nnf1TnRS8NvOTp4i9jn2jiXN8Xw4aCBZ8iIWSeWzCN6ulG51mp9eCzGCEotn17ovokT6OnDwiOuy/4Jn17E0MY9BmxygC5hTBvK1Jls4y8552MWf28Na8RPggqoae2Z8TDNiV86Z71fffrV49dRVHt+qRbpHFczT9VjvgKGa7+aZkWKSlw+5ZgBfasZfJYhoqcfC/du1lshE/kCCxSUZGAbXZn1GHVTiCWmRN53ccoUiiTAysJsxs1EtNmr5wPowbbgVRt5VUav8kuh6sDUcgzyEOWCi+mF12aD2Wy6evfk4r8jjGL1xOLVR5sbN5iUgKb7ZE00KIKhnaFlrKeIHs/kljYi+cPv8NrwMeNBCJpsiCRpkJt3ZHDiJiSn13pImGY6DtUBUpPkliPLjIf6EqG8Vn0H+u5vFfOorY0APOC5TOu3GNm71b5PgC8tManeSBqfq5Z+xY3vRNkvpoSC3U6TCSEavHjnghbp2eQfcNmIz73EpVkKmwm+RdQW/sO2rqlCyokX2/sM6qbBGwnNeKYu/yXJwJGCWiLT7EagLi1KOcJNCojbfs4TTLc4V0+VI6a7+14zAz+gPZKNKJe7nEONmc8ty88YsIcoHdpcd0y5+CAQ/VIxhbGFnASuLPEdkd3zySvtKiHo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
