travis:
  secure:
    BINSTAR_TOKEN: Gtdqb8HLD7zTCG7eekuvesrOwLzX15CtlRSo2eQ/popkJ6nj3CLxcZdFEIsVN65xsJkcXq2OOnGNAI5LotTT4AYleCUex0TL89vqj0t5ujJqHiRO3a94ulxE252eddBgAvgkFFYbdg0HdQiSbJ6CUJY/z7x2XLSeZUsbcAW8pmGasU8ZF5IS06MMFDVJ6tUAA09soiZDuB66L8Z+yVleDdA8GXaB2iykIWmYin/rhrR5u5ric4zZLIBAzUmEXqya04K6D9r5NzaerGesgr30S1AkxMPW4cQoh/2fJn6j/C4S1ZAOR/V0v9SWZN6XMslaCkG+au63yY5ovgo+QQg7jQGTTHHCCL5pSKL5vd7I6ALxL+X2UptRA9p9Fv8qgSV6oB2ZqGMcRFStJMLVOlW5RVRwCLlj9Jhh2t2qubBqjFuzUsmkk/56xhIcxDMdCfH97kLOMK/VJlrcdci4/IBlDnSOMuTYXhfdg4dY6mYb+84GUerPlLYhlMI+fcLBAWFUm0+HR8jinWIFhZ2CE27vrBUZBzSCvNjJ70YQ2Pg9XkPyTP8QmjW43YpcaWXUCiQUAGhUODSez8kUDs7L/vDpjxeISZBNd5SVKVf3bHPneiE+sgyi2++luBUBOxx6atwVMWZ5vSjv+wVvfigat/AHqzVJB0Tph7ebl8FAgvjVFIU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
