travis:
  secure:
    BINSTAR_TOKEN: AdSJxdkPddEEAYML5lFGPFgNNaRIOHiClbspV3J4shx52IyNyuE8caoCtH731CXA8PDJqcnSZaZ6kGE5B4H6lucTBh0Q/HFZMqd9QOZULVmZBU1CeclEz2vnZ9g/xQiCBdGbrg7/hy3s/z+0aCmllfVL79EWrpJDc9f/8IR3e8JCmp7Jg5iGDoFf5Kf+gIxD5j5o4vp/IxUij6KaQssVZmXZ/GJCbdv0PAyAGraQj/IFlV+gBeTxtm3aUYjv7BNy9TK8uYrhrVVmTNPCCipPq2eBeYjWYmbCM6uw32xx3cWNXZy+Wy0CBtFEUYSIbbowaiPt0wGUh7IdsvI6B0GDtx/NkP1xZsHitw0YhT5RyLAfJNju4Tig3EMdRJQvvweCzkTZXH1vNJ2VRHHWICfE1AWmdgx7pwHl0YGObf+kbM4UBHdIHI+VRSyVjw1Q6HhUiYKzgxK1+XstZ1a299JwmkLHC3xHtZVMZG9bkWoaBOsOJeIhQzTEAhqBRP6GzKKTwyl9V54GtFMxWhfzQAOZGro6MS9JThkwkpvB5XL/9qLqrlM0u9yFiFPJdrIOX9Bv/Z2MnVnRcl9fOmXRiU+e19JwzlKB8uWNRudO0lpdswrFW27nevl6C8I16vG7uq4cfLyP9K2ElnabhU40KrS0zjNtY9yiW3yil/OJjRK0QyU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
