travis:
  secure:
    BINSTAR_TOKEN: LbtU/ph5tLGI0fXKJj19SBhZrQTojagcaN0RtkGcNDWEMgPOxHgAcVGw7NzVqkypQ+8gNFErpA72nyasaB2YvVHke75hg9vLpUGJ+n1Cy57JKZcsQNYBd86h4mgQEJ/RppEnGM0pm5vhfGKlTTLD85RtzvYhVTuiXmh3fmq1NG+ivkBeI3Z1IhDlZswq67fvHR1qQ95nmXGR2rE4qBToS6dM1BwImKJxb0ZMVaR1tQH3RgZaiJqhGmMVs7caTU3U5GfTNenLpcg1uTziEX6ldcsdeHKoS5y4n0wi3/XzKnp5ktyWcAogD8jl6pvobza11zXc56rDxSDT09kCEw5HJ7Xug3xp5TcuP7gpwZXVb05rMNkPGhxYN9mWgEOPNcrIb9cq0mOe7kyRIiqZkW9NjCuYhMZsDWXrdQ1xkLPrhNDvFolQmjlXzZlnnUDd2jY7brQljHBcc2i2wNXSWl+66uiHCP8kfnYKqdDC/YYO2bPRhXsXs0zCzutGrggIh9iZIkrZIdwcoH9DKARXEis5X0cDenHVH9o8WXF10cNp0a8H38IQDT6pp6pGybg61fYZnFzeoEaOe6UaiTlMeGfpgMYYK0z3QJg8txqoGC6fRRyp0rhZxWHKXBICCwBYKMi2bauWTox5HeAwDbgnvfH4jBHEzXueFyhJDHrdnKrLdKA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
