travis:
  secure:
    BINSTAR_TOKEN: sKO8Bz29XU8pE/j8YHgPqGwzFh7hZWOemeDqHTCcgQKK16mAYITg/And4tI5czOn8WIDNvpdfiegA1xjHZxqJs4Le8YygQMlAnljUQtfcTBjVRVSILD7vsdX9BkOF+fKBW2JTkiDt1eGEak4RoRvu0fbviB+NWo3u2r7fwPhgXQAgR2CSQ0XA2lJq8HrpgzbAueOzTNVeiKNnkb1AaQYfnksJaQxi3nauWphWUpuRbVAzYxJZPc2GSPVigrdAPDwL5MbLNbCE4YFdVTs/jk+bOO8phPCnBXv/xsmvVeZqDv5cfPwp0vN2CGucnwY/JqHpfgGkJ+qZO4iTgi+qndi7xMU3QEH6nO7lXJPmVHhmDTndzqxovr465JbHZ0rJExHPIlQTQ1wSigshMBCNWemuyWNRW4VoYGvlxSkR+6/ltusd8bmqjnohuxqotLOjuizPvU0qOA9hFVMHGV7hzvJipvD77L8jg07w6ghqxIDIN078jripbCokcc/61xM3F4eugOq3sMjP50ogh1jQDeElwDbICOqKuQkcZyjS5ByhwC0tEcxN2A5r3cs/z1MVQPxp7rmNxQCSirV/qbDyIAUGWSkxR9IpDwkPkwxJwqWuQpt0+gtAMABoDZ5fUkj/qmHtNPaMRswTFqsHeyi2mS1XCM1chxW4DgkjbkcbZiwg8c=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
